apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          image: mongo:6
          volumeMounts:
            - mountPath: /data/db
              name: mongo-vol
          ports:
            - containerPort: 27017
      volumes:  
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: host-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
spec:
  selector:
    app: mongo-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
